# Translations template for neutron.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the neutron project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Neutron\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-19 06:08+0000\n"
"PO-Revision-Date: 2014-05-29 07:49+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Japanese (http://www.transifex.com/projects/p/neutron/"
"language/ja/)\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: neutron/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "除去される元の例外: %s"

#: neutron/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "予期せぬ例外が、%d回()発生しました。再試行中。"

#: neutron/openstack/common/periodic_task.py:179
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: neutron/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "RPCクリーンアップ中に例外が発生"

#: neutron/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "未処理例外"

#: neutron/openstack/common/db/api.py:72
msgid "DB exceeded retry limit."
msgstr "DBへのリトライが上限に達しました。"

#: neutron/openstack/common/db/api.py:76
msgid "DB connection error."
msgstr "DB接続エラーが発生しました。"

#: neutron/openstack/common/db/sqlalchemy/session.py:460
msgid "DB exception wrapped."
msgstr "DB 例外がラップされました。"

#: neutron/openstack/common/middleware/notifier.py:40
#, python-format
msgid "An exception occurred processing the API call: %s "
msgstr ""

#: neutron/openstack/common/rpc/amqp.py:480
#: neutron/openstack/common/rpc/impl_zmq.py:286
msgid "Exception during message handling"
msgstr "メッセージ処理中の例外"

#: neutron/openstack/common/rpc/common.py:88
msgid "Exception in string format operation"
msgstr "ストリング・フォーマットの操作で例外が発生しました"

#: neutron/openstack/common/rpc/common.py:292
#, python-format
msgid "Returning exception %s to caller"
msgstr "例外 %s を呼び出し元に返しています"

#: neutron/openstack/common/rpc/impl_kombu.py:156
msgid "Failed to process message ... skipping it."
msgstr "メッセージの処理に失敗しました... スキップしています。"

#: neutron/openstack/common/rpc/impl_kombu.py:160
msgid "Failed to process message ... will requeue."
msgstr "メッセージ処理が失敗しました…キューに再登録します。"

#: neutron/openstack/common/rpc/impl_kombu.py:571
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""
"%(hostname)s:%(port)d 上の AMQP サーバーは到達不能です: "
"%(err_str)s。%(sleep_time)d 秒後に再試行します。"

#: neutron/openstack/common/rpc/impl_kombu.py:625
#: neutron/openstack/common/rpc/impl_qpid.py:575
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""
"トピック '%(topic)s' のコンシューマーを宣言できませんでした: %(err_str)s"

#: neutron/openstack/common/rpc/impl_kombu.py:647
#: neutron/openstack/common/rpc/impl_qpid.py:594
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr "キューからのメッセージのコンシュームに失敗しました: %s"

#: neutron/openstack/common/rpc/impl_kombu.py:686
#: neutron/openstack/common/rpc/impl_qpid.py:629
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""
"トピック '%(topic)s' に対してメッセージをパブリッシュできませんでした: "
"%(err_str)s"

#: neutron/openstack/common/rpc/impl_qpid.py:191
msgid "Failed to process message... skipping it."
msgstr "メッセージの処理に失敗しました... スキップしています。"

#: neutron/openstack/common/rpc/impl_qpid.py:517
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""
"AMQP サーバーに接続できません: %(e)s。%(delay)s 秒間スリープ状態になります"

#: neutron/openstack/common/rpc/impl_qpid.py:602
msgid "Error processing message.  Skipping it."
msgstr "メッセージの処理中にエラーが発生しました。スキップしています。"

#: neutron/openstack/common/rpc/impl_zmq.py:96
msgid "JSON serialization failed."
msgstr "JSON の直列化が失敗しました。"

#: neutron/openstack/common/rpc/impl_zmq.py:195
msgid "ZeroMQ socket could not be closed."
msgstr "ZeroMQソケットをクローズできませんでした。"

#: neutron/openstack/common/rpc/impl_zmq.py:339
msgid "RPC message did not include method."
msgstr "RPC メッセージにメソッドが含まれていませんでした。"

#: neutron/openstack/common/rpc/impl_zmq.py:476
msgid "Topic socket file creation failed."
msgstr "トピック・ソケット・ファイルの作成に失敗しました。"

#: neutron/openstack/common/rpc/impl_zmq.py:482
#, python-format
msgid ""
"Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""
"トピック %(topic)s のトピック単位のローカル・バックログ・バッファーがフルで"
"す。メッセージを除去しています。"

#: neutron/openstack/common/rpc/impl_zmq.py:498
#, python-format
msgid "Required IPC directory does not exist at %s"
msgstr "必要な IPC ディレクトリが %s に存在しません"

#: neutron/openstack/common/rpc/impl_zmq.py:507
#, python-format
msgid "Permission denied to IPC directory at %s"
msgstr "IPC ディレクトリ %s へのアクセス許可がありません"

#: neutron/openstack/common/rpc/impl_zmq.py:510
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""
"ZeroMQ 受信側デーモンを作成できませんでした。ソケットが既に使用中である可能性"
"があります。"

#: neutron/openstack/common/rpc/impl_zmq.py:563
msgid "ZMQ Envelope version unsupported or unknown."
msgstr "ZMQ エンベロープのバージョンがサポートされないか、不明です。"
